### ISSUE TITLE
How to wait for commands?

### ISSUE THREAD

**Issue by jkroepke** [Jamie-/openvpn-api#23]
Hi!

I'm write a small management interface script which allows me to handle some authentication stuff. I have to set `management-client-auth` on the openvpn server.

How to wait for an incoming request?

**Comment by Jamie-** [comment]
Currently this functionality is not yet supported by this library. There is a pull request (#14) open for the beginning of this feature which will enable you to do what you ask. Keep an eye on that PR and I'll try to remember to write back here after it's merged.

**Comment by jkroepke** [comment]
Thanks a lot!
